version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.12-management  # Management plugin included
    container_name: rabbitmq
    restart: unless-stopped  # Auto-recover on crashes
    ports:
      - "5672:5672"    # AMQP protocol
      - "15672:15672"  # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin       # Default credentials
      RABBITMQ_DEFAULT_PASS: password123 # Change in production!
      RABBITMQ_DEFAULT_VHOST: /          # Explicit default virtual host
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent message storage

volumes:
  rabbitmq_data:  # Named volume for message durability